import { execSync } from 'node:child_process';
import { existsSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const run = (cmd) => {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  } catch (error) {
    return error.stdout?.toString().trim() || error.stderr?.toString().trim() || error.message;
  }
};

const files = run("git ls-files ':!:node_modules' ':!:game-repo/node_modules'").split('\n').filter(Boolean);
const largeFiles = files
  .map((file) => ({ file, bytes: statSync(file).size }))
  .filter(({ bytes }) => bytes > 250_000)
  .sort((a, b) => b.bytes - a.bytes);

const duplicateCandidates = files.filter((file) => file.startsWith('game-repo/') && existsSync(file.replace('game-repo/', '')));
const status = run('git status --short');
const audit = run('npm audit --omit=dev --audit-level=moderate');

const markdown = `# Repository Health Dashboard\n\nGenerated by \`npm run repo:health\`.\n\n## Build Health\n\n- Git status: ${status ? 'working tree has changes' : 'clean'}\n- Type check command: \`npm run lint\`\n- Build command: \`npm run build\`\n\n## Repository Shape\n\n- Tracked files: ${files.length}\n- Duplicate mirrored files under \`game-repo/\`: ${duplicateCandidates.length}\n- Large tracked files over 250 KB: ${largeFiles.length}\n\n${largeFiles.length ? largeFiles.map(({ file, bytes }) => `- ${file}: ${(bytes / 1024).toFixed(1)} KB`).join('\n') : '- None detected.'}\n\n## Dependency and Security Signal\n\n\`\`\`text\n${audit.slice(0, 4000) || 'npm audit produced no output.'}\n\`\`\`\n\n## Open Risks\n\n- Root app and \`game-repo/\` mirror the same application files; this raises maintenance cost until one source of truth is chosen.\n- Production bundle currently exceeds the default Vite chunk warning threshold; see \`docs/performance.md\`.\n- Coverage is not yet enforced because no test runner dependency is installed.\n`;

writeFileSync(join('docs', 'repository-health.md'), markdown);
console.log('Wrote docs/repository-health.md');
