import { execSync } from 'node:child_process';
import { readFileSync, statSync, writeFileSync } from 'node:fs';

const run = (cmd) => execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
const files = run("git ls-files ':!:node_modules' ':!:game-repo/node_modules'").split('\n').filter(Boolean);
const sourceFiles = files.filter((file) => /\.(ts|tsx|js|jsx|css|md)$/.test(file));
const docs = files.filter((file) => file.startsWith('docs/') || file === 'README.md');
const loc = sourceFiles.reduce((sum, file) => sum + readFileSync(file, 'utf8').split('\n').length, 0);
const largest = sourceFiles
  .map((file) => ({ file, lines: readFileSync(file, 'utf8').split('\n').length, bytes: statSync(file).size }))
  .sort((a, b) => b.lines - a.lines)
  .slice(0, 10);
const todos = sourceFiles.flatMap((file) =>
  readFileSync(file, 'utf8')
    .split('\n')
    .map((line, index) => ({ file, line: index + 1, text: line.trim() }))
    .filter((item) => /\b(TODO|FIXME|HACK)\b/i.test(item.text)),
);
const mostChanged = run('git log --name-only --pretty=format: -- . | sed /^$/d | sort | uniq -c | sort -nr | head -10') || 'No history.';

const markdown = `# Repository Metrics\n\nGenerated by \`npm run repo:stats\`.\n\n## Counts\n\n- Tracked files: ${files.length}\n- Source/doc files counted for LOC: ${sourceFiles.length}\n- Lines of code/docs: ${loc}\n- Documentation files: ${docs.length}\n- Documentation coverage proxy: ${((docs.length / Math.max(files.length, 1)) * 100).toFixed(1)}% of tracked files are docs or README\n- Tests: ${files.filter((file) => /\.(test|spec)\.(ts|tsx|js|jsx)$/.test(file)).length}\n- Coverage: Not available until test runner is installed\n\n## Largest Modules\n\n${largest.map((item) => `- ${item.file}: ${item.lines} lines, ${(item.bytes / 1024).toFixed(1)} KB`).join('\n')}\n\n## Oldest TODOs\n\n${todos.length ? todos.slice(0, 10).map((item) => `- ${item.file}:${item.line} — ${item.text}`).join('\n') : '- None detected.'}\n\n## Most Changed Files\n\n\`\`\`text\n${mostChanged}\n\`\`\`\n\n## GitHub Metrics\n\n- Open issues: Requires GitHub API enrichment.\n- Closed issues: Requires GitHub API enrichment.\n- Average PR size: Requires GitHub API enrichment.\n`;

writeFileSync('docs/metrics.md', markdown);
console.log('Wrote docs/metrics.md');
