import fs from 'node:fs/promises';
import path from 'node:path';

export async function writeArtifacts(baseDir, payload) {
  await fs.mkdir(baseDir, { recursive: true });
  const patch = buildPatch(payload);
  const files = {
    'codex-task.md':        payload.codexPrompt,
    'antigravity-repair-task.md': payload.repairPrompt,
    'pr-package.md':        payload.prMarkdown,
    'execution.json':       JSON.stringify(payload.executionPacket, null, 2),
    'changes.patch':        patch,
  };
  const written = [];
  for (const [name, content] of Object.entries(files)) {
    const fullPath = path.join(baseDir, name);
    await fs.writeFile(fullPath, content, 'utf8');
    written.push(fullPath);
  }
  return written;
}

export async function writeUserArtifact(baseDir, filename, content) {
  await fs.mkdir(baseDir, { recursive: true });
  const safeName = filename.replace(/[^a-zA-Z0-9._-]/g, '_');
  const fullPath = path.join(baseDir, safeName);
  await fs.writeFile(fullPath, content, 'utf8');
  return fullPath;
}

function buildPatch(payload) {
  const { executionPacket, codexPrompt, repairPrompt } = payload;
  const repo   = executionPacket?.repo   || 'unknown/repo';
  const branch = executionPacket?.branch || 'simba/patch';
  const now    = new Date().toUTCString();

  const filesToCreate = (executionPacket?.files_to_create || []).map(f => [
    `diff --git a/${f} b/${f}`, `new file mode 100644`, `--- /dev/null`, `+++ b/${f}`,
    `@@ -0,0 +1 @@`, `+# Generated by bot — see codex-task.md for full prompt`,
  ].join('\n'));

  const filesToModify = (executionPacket?.files_to_modify || []).map(f => [
    `diff --git a/${f} b/${f}`, `--- a/${f}`, `+++ b/${f}`,
    `@@ -1,1 +1,1 @@`, `-# existing content`, `+# modified — see antigravity-repair-task.md`,
  ].join('\n'));

  return [
    `# Bot Generated Patch`,
    `# Repo:   ${repo}`,
    `# Branch: ${branch}`,
    `# Date:   ${now}`,
    `#`,
    `# HOW TO APPLY`,
    `# 1. Run Codex/Antigravity with codex-task.md`,
    `# 2. Save generated files to paths below`,
    `# 3. git add . && git commit -m "${branch.replace('simba/', 'feat: ')}"`,
    `# 4. git push origin ${branch}`,
    `#`,
    `# CODEX SUMMARY`,
    `# ${codexPrompt.split('\n')[0]}`,
    '',
    ...(filesToCreate.length ? filesToCreate : ['# No new files declared']),
    '',
    ...(filesToModify.length ? filesToModify : ['# No modified files declared']),
  ].join('\n');
}
